---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mcsps-webex-receiver
  name: mcsps-webex-receiver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mcsps-webex-receiver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mcsps-webex-receiver
    spec:
      containers:
      - image: mtr.external.otc.telekomcloud.com/mcsps/python-flask:latest
        imagePullPolicy: IfNotPresent
        name: stats
        ports:
          - containerPort: 9091
        command: ["sh","-c"]
        args: ["git clone https://github.com/mcsps/alertmanager-webhook-webex-teams.git && cd alertmanager-webhook-webex-teams/$APP && gunicorn --bind 0.0.0.0:9091 --access-logfile /dev/stdout wsgi:app"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: APP
          value: "webex"
        - name: WEBEX_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcsps-webex-receiver
              key: WEBEX_TOKEN
        - name: WEBEX_ROOM
          valueFrom:
            secretKeyRef:
              name: mcsps-webex-receiver
              key: WEBEX_ROOM
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
